insert into animali (id, specie, problema , costoCure) values (1, 'Phalacrocorax brasilianus', 'cancro', 339);
insert into animali (id, specie, problema , costoCure) values (2, 'Hymenolaimus malacorhynchus', 'cancro', 177);
insert into animali (id, specie, problema , costoCure) values (3, 'Cracticus nigroagularis', 'dermatite', 175);
insert into animali (id, specie, problema , costoCure) values (4, 'Carduelis uropygialis', 'pulci', 288);
insert into animali (id, specie, problema , costoCure) values (5, 'Ramphastos tucanus', 'frattura', 77);
insert into animali (id, specie, problema , costoCure) values (6, 'Choloepus hoffmani', 'frattura', 284);
insert into animali (id, specie, problema , costoCure) values (7, 'Mazama gouazoubira', 'cancro', 238);
insert into animali (id, specie, problema , costoCure) values (8, 'Elephas maximus bengalensis', 'cancro', 32);
insert into animali (id, specie, problema , costoCure) values (9, 'Meleagris gallopavo', 'frattura', 66);
insert into animali (id, specie, problema , costoCure) values (10, 'Spilogale gracilis', 'pulci', 211);
insert into animali (id, specie, problema , costoCure) values (11, 'Dasypus novemcinctus', 'dermatite', 258);
insert into animali (id, specie, problema , costoCure) values (12, 'Libellula quadrimaculata', 'dermatite', 51);
insert into animali (id, specie, problema , costoCure) values (13, 'unavailable', 'frattura', 359);
insert into animali (id, specie, problema , costoCure) values (14, 'Eudromia elegans', 'dermatite', 231);
insert into animali (id, specie, problema , costoCure) values (15, 'Chlamydosaurus kingii', 'pulci', 212);
insert into animali (id, specie, problema , costoCure) values (16, 'Herpestes javanicus', 'frattura', 278);
insert into animali (id, specie, problema , costoCure) values (17, 'Chlidonias leucopterus', 'dermatite', 30);
insert into animali (id, specie, problema , costoCure) values (18, 'Platalea leucordia', 'frattura', 236);
insert into animali (id, specie, problema , costoCure) values (19, 'Cynictis penicillata', 'frattura', 81);
